#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg &

pgrep -x unclutter > /dev/null || unclutter &

pgrep -x picom > /dev/null || picom -f -D 3 &

monitors=$(xrandr --listmonitors | rg 'Monitors: ' | cut -d ' ' -f 2)

if [ $monitors -gt 1 ]; then
    xrandr --output DisplayPort-0 --auto --primary --output HDMI-A-0 --auto --left-of DisplayPort-0
fi

if [ $monitors -gt 1 ]; then
    bspc monitor DisplayPort-0 -d 1 2 3 4 5
    bspc monitor HDMI-A-0 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding         32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
