#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg &

pgrep -x unclutter > /dev/null || unclutter &

pgrep -x picom > /dev/null || picom -f -D 3 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding         32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
