alias copyhash='git lg | head -n 1 | cut -d ' ' -f 1 | pbcopy'
alias gossh='eval `keychain --eval --nogui --agents gpg,ssh id_rsa DFBFC992`'
alias ll='nnn -de'
alias ls='ls --color=auto'
alias lsl='ls -l --si'
alias md='mkdir -p'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias rmd='rm -r'
alias t='tree -L 2 --filelimit 50'
alias top='htop'
alias tt='tree -L 4 --filelimit 30'
